version: '2'
volumes:
  craftcms-data:
  postgresql-data:
  craftcms-logs:
services:
  web:
    build: craft
    image: craftcms:latest
    ports:
      - 6060:80
    volumes:
      - craftcms-logs:/var/log
      - craftcms-data:/usr/share/nginx
    links:
      - postgres
    environment:
      DATABASE_URL: postgresql://craft3:secret@postgres/craft3
      LANG: C.UTF-8

  postgres:
    image: postgres:10.5
    environment:
      POSTGRES_USER: craft3
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: craft3
      POSTGRES_INITDB_ARGS: "-E UTF8"
    volumes:
      - postgresql-data:/var/lib/postgresql/data